CREATE DATABASE IF NOT EXISTS test;

USE test;

CREATE TABLE IF NOT EXISTS User (
   ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
   email VARCHAR(40) NOT NULL,
   password VARCHAR(40) NOT NULL
 );
